/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taskmanager;

import java.io.IOException;
import java.util.logging.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author ahmed maher
 */
public class PackageManager extends javax.swing.JFrame {

    private String packageName;

    public PackageManager() {
        this("dpkg-query -l");
    }

    public PackageManager(String cmd) {
        initComponents();
        try {
            this.getTableIntialized(cmd);
        } catch (IOException ex) {
            Logger.getLogger(PackageManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getTableIntialized(String command) throws IOException {
        String[] lines = TaskManager.strFormatter(TaskManager.bashTerminal(command));
        
        String[] tableHeaders = TaskManager.splice(lines[3].split(" "), 0);
        int length = tableHeaders.length;

        boolean[] cell_editable = new boolean[length];
        for (int i = 0; i < length; i++) {
            cell_editable[i] = false;
        }

        jTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                tableHeaders
        ) {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return cell_editable[columnIndex];
            }
        });

        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        for (int i = 5; i < lines.length; i++) {
            model.addRow(TaskManager.splice(lines[i].split(" "), 0));
        }

        jLabel_PckgCount.setText(model.getRowCount() + " Installed Package");
        jTable.getColumnModel().getColumn(0).setPreferredWidth(200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_UninstallPckg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel_Pckg = new javax.swing.JLabel();
        jLabel_PckgCount = new javax.swing.JLabel();
        jButton_Uninstall = new javax.swing.JButton();

        jButton_UninstallPckg.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jButton_UninstallPckg.setText("uninstall");
        jButton_UninstallPckg.setEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Package Manager");
        setLocation(new java.awt.Point(300, 100));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTable.setBackground(new java.awt.Color(0, 0, 0));
        jTable.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTable.setForeground(new java.awt.Color(51, 255, 51));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jLabel_Pckg.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabel_Pckg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel_PckgCount.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel_PckgCount.setForeground(new java.awt.Color(0, 102, 0));
        jLabel_PckgCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton_Uninstall.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButton_Uninstall.setForeground(new java.awt.Color(204, 0, 0));
        jButton_Uninstall.setText("uninstall");
        jButton_Uninstall.setEnabled(false);
        jButton_Uninstall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UninstallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_PckgCount, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Pckg, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Uninstall, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Pckg, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel_PckgCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Uninstall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        try {
            int row_index = jTable.getSelectedRow();
            if (row_index > -1) {
                TableModel model = jTable.getModel();

                this.packageName = model.getValueAt(row_index, 0).toString();
                String version = model.getValueAt(row_index, 1).toString();
                String architecture = model.getValueAt(row_index, 2).toString();
                String description = model.getValueAt(row_index, 3).toString();

                jLabel_Pckg.setText("Package [ " + this.packageName + " ] : Version [ " + version + " ] : Arch [ " + architecture + " ] : Desc [ " + description + " ]");
                jButton_Uninstall.setEnabled(true);
            }
        } catch (NumberFormatException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jButton_UninstallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UninstallActionPerformed
        TerminalWindow terminal = new TerminalWindow(TaskManagerGUI.rootCommand + "apt-get remove " + this.packageName + " --yes");
        JOptionPane.showMessageDialog(null, "Hold on, it takes time.\nDon't go away", "Message", JOptionPane.INFORMATION_MESSAGE);
        terminal.show();

        jLabel_Pckg.setText("");
        jButton_Uninstall.setEnabled(false);
    }//GEN-LAST:event_jButton_UninstallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PackageManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PackageManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PackageManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PackageManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PackageManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Uninstall;
    private javax.swing.JButton jButton_UninstallPckg;
    private javax.swing.JLabel jLabel_Pckg;
    private javax.swing.JLabel jLabel_PckgCount;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
